name: Import translations from Crowdin

on:
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup Crowdin CLI
        run: |
          npm i -g @crowdin/cli

      - name: Pull from Crowdin
        run: |
          CROWDIN_TOKEN=${{ secrets.CROWDIN_TOKEN }} ./crowdin-pull.sh

      - name: Pull origin
        run: git pull origin main --ff-only # Pull origin in case a commit has been done while updating

      # This makes sure that the site actually builds before pushing to the repo
      - name: Build site
        run: npm run docs:build

      - name: Push changes
        run: |
          git config user.email "flamekat54@aol.com"
          git config user.name "TWLBot"

          echo "machine github.com" > "$HOME/.netrc"
          echo "  login TWLBot" >> "$HOME/.netrc"
          echo "  password ${{ secrets.TWLBOT_TOKEN }}" >> "$HOME/.netrc"

          echo "machine api.github.com" >> "$HOME/.netrc"
          echo "  login TWLBot" >> "$HOME/.netrc"
          echo "  password ${{ secrets.TWLBOT_TOKEN }}" >> "$HOME/.netrc"

          git checkout main
          git stage .
          if git commit -m "Automatic translation import"; then
            git push origin main
          fi
